### ISSUE TITLE
UTF-8 codec error

### ISSUE THREAD

**Issue by soviet9922** [fragtastic/cis-benchmark-to-csv#14]
Hi when i try to parse a pdf file from cis always got this error:
soviet@ubuntuvm:~/Documents/cis-benchmark-converter-master$ python3 cis2excel.py cis2019.pdf 
INFO:root:Writing to "cis2019.xlsx"
INFO:root:Parsing cis2019.pdf
Traceback (most recent call last):
  File "cis2excel.py", line 5, in <module>
    cce = CISConverterExcel()
  File "/home/soviet/Documents/cis-benchmark-converter-master/cisconverter/__init__.py", line 189, in __init__
    self.parse_text()
  File "/home/soviet/Documents/cis-benchmark-converter-master/cisconverter/__init__.py", line 77, in parse_text
    for line in inFile:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 11: invalid start byte

**Comment by fragtastic** [comment]
This uses text dumps only.
Not the PDF directly.

**Comment by fragtastic** [comment]
@soviet9922 I'll add these instructions to the readme too.
In Adobe Acrobat DC -> File -> Export To -> Text (Plain)
Ensure export is set to Settings -> UTF-8
Uncheck "View Result"

This should give you a format that works.
