### ISSUE TITLE
Unicode Error - UTF8 Encoding Scheme

### ISSUE THREAD

**Issue by deFr0ggy** [fragtastic/cis-benchmark-to-csv#17]
Tried to run the script though its returning the below error!

```
python3 cis-benchmark-converter/cis2csv.py CIS_Microsoft_Windows_Server_2016_Benchmark_v1.4.0.pdf 
INFO:root:Writing to CIS_Microsoft_Windows_Server_2016_Benchmark_v1.4.0.csv
INFO:root:Parsing CIS_Microsoft_Windows_Server_2016_Benchmark_v1.4.0.pdf
Traceback (most recent call last):
  File "cis-benchmark-converter/cis2csv.py", line 5, in <module>
    ccc = CISConverterCSV()
  File "/Users/frogman/Downloads/cis-benchmark-converter/cisconverter/__init__.py", line 164, in __init__
    self.parse_text()
  File "/Users/frogman/Downloads/cis-benchmark-converter/cisconverter/__init__.py", line 82, in parse_text
    for line in inFile:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 11: invalid start byte
```

**Comment by deFr0ggy** [comment]
Also tried, ignoring the errors and replacing them. Seems like the results are not being written. 

@fragtastic @smith-daniels 

```
python3 cis-benchmark-converter/cis2csv.py CIS_Microsoft_Windows_Server_2016_Benchmark_v1.4.0.pdf 
INFO:root:Writing to CIS_Microsoft_Windows_Server_2016_Benchmark_v1.4.0.csv
INFO:root:Parsing CIS_Microsoft_Windows_Server_2016_Benchmark_v1.4.0.pdf
INFO:root:Total lines: 84062
INFO:root:Written Rows: 0
```

**Comment by fragtastic** [comment]
@deFr0ggy The problem is that a PDF is being provided instead of a text dump. The readme explains correct usage.
